import { Router } from "express";
import { createMaterial } from "../controllers/materials/createMaterials.controller.js";
import { getMaterials } from "../controllers/materials/getMaterials.controllers.js";
import { updateMaterial } from "../controllers/materials/updateMaterial.controller.js";
import { getMaterial } from "../controllers/materials/getMaterial.controllers.js";
import { deleteMaterial } from "../controllers/materials/deleteMaterial.controllers.js";
import { validateCreateMaterial } from "../validators/validateCreateMaterial.js";
import { validateUpdateMaterial } from "../validators/validateUpdateMaterial.js";
import { handleValidationErrors } from "../libs/handleValidationErrors.js";
import verifyToken from "../libs/verifyToken.js";
const router = Router();
router.post("/material",verifyToken,validateCreateMaterial,handleValidationErrors,createMaterial);
router.patch("/material",verifyToken,validateUpdateMaterial,handleValidationErrors,updateMaterial);
router.get("/materials",getMaterials);
router.get("/material/:idMaterial",verifyToken,getMaterial);
router.delete("/material/:idMaterial",verifyToken,deleteMaterial);
export default router;