@api=  http://localhost:3000/api
GET  {{api}}/users
###
GET  {{api}}/user/55a40cc846399cb276ab3c91446612d0
###
GET  {{api}}/user/email/a20170094@utem.edu.mx
#### 
POST {{api}}/user
content-type:application/json

{
    "name": "josuemagico",
    "lastName":"morfin",
    "password":"123456",
    "email":"yioootakucosplay@gmail.com",
    "birthDate":"1998-08-29"
}
###
PUT {{api}}/user/validate
content-type:application/json

{
    "uid":"2660376e-dbf8-44c1-b69f-b2554e3e5d4c"
}
###
POST {{api}}/login
content-type:application/json

{
    "password":"123456",
    "email":"yioootakucosplay@gmail.com"
}
###
POST {{api}}/user/menu
content-type:application/json

{
    "idUser":"b31e1fde35d839a5277c40dce048ebf7"
}